import jsPDF from "jspdf";

export const generatePrescriptionPDF = (booking: any, prescriptionText: string) => {
  const doc = new jsPDF();

  // Safety Checks
  const docName = booking.specialist?.name || "Doctor";
  const docCat = booking.specialist?.category || "Specialist";
  // Fallback: If familyMember exists use it, otherwise try booking.user, otherwise "Patient"
  const patientName = booking.familyMember?.name || booking.user?.name || "Patient";
  const dateStr = new Date(booking.date).toLocaleDateString();

  // Header
  doc.setFontSize(22);
  doc.text("ReviveHub Prescription", 105, 20, { align: "center" });
  
  doc.setFontSize(12);
  doc.text(`Dr. ${docName}`, 14, 40);
  doc.text(`Specialty: ${docCat}`, 14, 46);
  
  doc.text(`Patient: ${patientName}`, 140, 40);
  doc.text(`Date: ${dateStr}`, 140, 46);

  // Line
  doc.setLineWidth(0.5);
  doc.line(10, 55, 200, 55);

  // Content
  doc.setFontSize(14);
  doc.text("Rx / Advice:", 14, 70);
  
  doc.setFontSize(12);
  // Wrap text to avoid cutoff
  const lines = doc.splitTextToSize(prescriptionText || "No notes provided.", 180);
  doc.text(lines, 14, 80);

  // Footer
  doc.setFontSize(10);
  doc.text("Generated by ReviveHub Digital Health", 105, 280, { align: "center" });

  doc.save(`Prescription_${booking.id}.pdf`);
};