import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePrescriptionPDF = (booking: any, prescriptionText: string) => {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(22);
  doc.text("ReviveHub Prescription", 105, 20, { align: "center" });
  
  doc.setFontSize(12);
  doc.text(`Dr. ${booking.specialist.name}`, 14, 40);
  doc.text(`Specialty: ${booking.specialist.category}`, 14, 46);
  
  doc.text(`Patient: ${booking.familyMember?.name || booking.user.name}`, 140, 40);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 140, 46);

  // Content
  doc.setLineWidth(0.5);
  doc.line(10, 55, 200, 55);

  doc.setFontSize(14);
  doc.text("Rx / Advice:", 14, 70);
  
  doc.setFontSize(12);
  const lines = doc.splitTextToSize(prescriptionText, 180);
  doc.text(lines, 14, 80);

  // Footer
  doc.setFontSize(10);
  doc.text("Generated by ReviveHub Digital Platform", 105, 280, { align: "center" });

  doc.save(`Prescription_${booking.id}.pdf`);
};